"use strict";
const apiBase="/api/admin/v1";let csrfToken="";
const byId=id=>document.getElementById(id);
function showNotice(message,isError=false){const notice=byId("notice");notice.textContent=message;notice.classList.toggle("error",isError);notice.hidden=false}
function clearNotice(){byId("notice").hidden=true}
function showLogin(){csrfToken="";byId("console").hidden=true;byId("account-actions").hidden=true;byId("login-panel").hidden=false;byId("password").value=""}
function showConsole(user){byId("current-user").textContent=user.username;byId("login-panel").hidden=true;byId("console").hidden=false;byId("account-actions").hidden=false}
async function api(path,options={}){const headers={Accept:"application/json",...(options.headers||{})};if(options.body)headers["Content-Type"]="application/json";if(csrfToken&&options.method&&options.method!=="GET")headers["X-CSRF-Token"]=csrfToken;const response=await fetch(apiBase+path,{credentials:"same-origin",...options,headers});if(response.status===401){showLogin();throw new Error("请重新登录")};if(response.status===503)throw new Error("服务暂时不可用，请稍后重试");if(!response.ok)throw new Error("操作失败，请检查输入后重试");if(response.status===204)return null;return response.json()}
function cell(row,value){const element=document.createElement("td");element.textContent=value??"—";row.appendChild(element);return element}
function formatTime(value){return value?new Date(value).toLocaleString("zh-CN",{hour12:false}):"永不过期"}
function statusText(value){return value==="active"?"已启用":"已停用"}
function renderDevices(devices){const list=byId("device-list");list.replaceChildren();byId("device-count").textContent=`${devices.length} 台设备`;for(const device of devices){const row=document.createElement("tr");cell(row,device.id);cell(row,device.label||"未命名");const status=cell(row,statusText(device.status));status.className=`status ${device.status}`;cell(row,formatTime(device.expires_at));cell(row,device.last_authenticated_at?formatTime(device.last_authenticated_at):"尚未连接");const actions=cell(row,"");actions.className="actions";const toggle=document.createElement("button");toggle.type="button";toggle.textContent=device.status==="active"?"停用":"启用";if(device.status==="active")toggle.className="danger";toggle.addEventListener("click",async()=>{if(device.status==="active"&&!confirm("停用会立即断开在线设备，确定继续？"))return;await run(()=>api(`/devices/${device.id}/status`,{method:"PUT",body:JSON.stringify({status:device.status==="active"?"disabled":"active"})}),"状态已更新")});actions.appendChild(toggle);const expiry=document.createElement("input");expiry.value=device.expires_at||"never";expiry.setAttribute("aria-label","设备到期时间");actions.appendChild(expiry);const save=document.createElement("button");save.type="button";save.textContent="更新到期";save.addEventListener("click",async()=>{if(!confirm("确定更新这台设备的到期时间？"))return;await run(()=>api(`/devices/${device.id}/expiry`,{method:"PUT",body:JSON.stringify({expires_at:expiry.value})}),"到期时间已更新")});actions.appendChild(save);list.appendChild(row)}}
function renderEvents(events){const list=byId("audit-list");list.replaceChildren();for(const event of events){const row=document.createElement("tr");cell(row,formatTime(event.created_at));cell(row,event.device_id);cell(row,event.action);cell(row,event.actor_type);cell(row,event.reason_code);list.appendChild(row)}}
async function loadData(){const [devices,events]=await Promise.all([api("/devices"),api("/device-events")]);renderDevices(devices.devices);renderEvents(events.events)}
async function run(operation,success){clearNotice();try{await operation();showNotice(success);await loadData()}catch(error){showNotice(error.message,true)}}
byId("login-form").addEventListener("submit",async event=>{event.preventDefault();const username=byId("username").value;const password=byId("password").value;byId("password").value="";try{const result=await api("/session",{method:"POST",body:JSON.stringify({username,password})});csrfToken=result.csrf_token;showConsole(result.user);await loadData()}catch(error){showNotice(error.message,true)}});
byId("device-form").addEventListener("submit",async event=>{event.preventDefault();const credential=byId("credential").value;const label=byId("device-label").value;const status=byId("device-status").value;const expires_at=byId("device-expiry").value;byId("credential").value="";await run(()=>api("/devices",{method:"POST",body:JSON.stringify({credential,label,status,expires_at})}),"设备已添加")});
byId("password-form").addEventListener("submit",async event=>{event.preventDefault();const current_password=byId("current-password").value;const new_password=byId("new-password").value;byId("current-password").value="";byId("new-password").value="";try{const result=await api("/me/password",{method:"PUT",body:JSON.stringify({current_password,new_password})});csrfToken=result.csrf_token;showNotice("密码已修改，当前会话已更新")}catch(error){showNotice(error.message,true)}});
byId("logout-button").addEventListener("click",async()=>{try{await api("/session",{method:"DELETE"})}finally{showLogin()}});byId("refresh-button").addEventListener("click",()=>run(loadData,"数据已刷新"));
(async()=>{try{const result=await api("/me");csrfToken=result.csrf_token;showConsole(result.user);await loadData()}catch(_){showLogin()}})();
